<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <title>DowaZoo</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
      crossorigin="anonymous"
    />
    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
      integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
      integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
      crossorigin="anonymous"
    ></script>

    <link
    rel="stylesheet"
    href="https://use.fontawesome.com/releases/v5.14.0/css/all.css"
    integrity="sha384-HzLeBuhoNPvSl5KYnjx0BT+WB0QEEqLprO+NBkkk5gbc67FTaL7XIGa2w1L0Xbgc"
    crossorigin="anonymous"
  />
  
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
    <script src="https://raw.githubusercontent.com/anseki/eager-image-loader/master/eager-image-loader.min.js"></script> 
  

    <style>
      body {
        font-family: "IBMPlexSansKR-Text";
      }

      .funding-pageSelector {
        font-weight: bold;

        color: #666;
        font-size: 1.1rem;
      }

      @font-face {
        font-family: "IBMPlexSansKR-Text";
        src: url("https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_20-07@1.0/IBMPlexSansKR-Text.woff")
          format("woff");
        font-weight: normal;
        font-style: normal;
      }

      .carousel-item {
        height: 20rem;
        width: 100%;
      }

      .container {
      }
      .circleImg {
        border-radius: 50%;
      }
      .img-container {
        margin-top: 1.5%;
      }

      .category-wrap{
        text-align: center;
      }

      .category-context{
        margin-top: 6%;
        margin-left: 7%;
      }

      .search_all {
      }

      .select_all {
        
        font-size: 1.4rem;
        font-weight: bold;
      }

      .funding_menu{
        margin-top: 2%;
        margin-bottom: 2%;
      }

      .now{
        color: black;
      }
	
	
	
@keyframes ldio-fh2riys9cfu {
    0%    { transform: translate(2px,2px) }
   33.33% { transform: translate(102px,2px) }
   66.66% { transform: translate(42px,102px) }
  100%    { transform: translate(2px,2px) }
}


.ldio-fh2riys9cfu > div {
  transform: scale(0.8);
  transform-origin: 100px 100px;
}

.ldio-fh2riys9cfu > div > div {
  animation: ldio-fh2riys9cfu 1s linear infinite;
  position: absolute
}

.ldio-fh2riys9cfu > div > div div:nth-child(1) {
  width: 72px;
  height: 72px;
  border-radius: 50%;
  border: 12px solid #e90c59;
  background: #46dff0
}

.ldio-fh2riys9cfu > div > div div:nth-child(2) {
  width: 17px;
  height:  51px;
  transform: rotate(-45deg);
  background: #e90c59;
  border-radius: 0 0 8px 8px;
  position: absolute;
  top: 68px;
  left: 85px
}
.loadingio-spinner-magnify-6i1erl5311d {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: #ffffff;
}
.ldio-fh2riys9cfu {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-fh2riys9cfu div { box-sizing: content-box; }
/* generated by https://loading.io/ */


    </style>

  
  </head>
  <body>
  
	<jsp:include page="/WEB-INF/views/common/header.jsp"/>
  
    <div class="container">
      <div class="row funding-pageSelector">
        <div class="col-lg-2 col-sm-2 col-md-2 funding_menu"></div>

        <div class="col-lg-2 col-sm2 col-md-2 funding_menu"> <span class="now">펀딩 홈</span></div>
        <div class="col-lg-2 col-sm-2 col-md-2 funding_menu">카테고리</div>
        <div class="col-lg-2 col-sm-2 col-md-2 funding_menu">오픈예정</div>
        <div class="col-lg-2 col-sm-2 col-md-2 funding_menu">글로벌</div>

        <div class="col-lg-2 col-sm-2 col-md-2 funding_menu"></div>
      </div>
    </div>

    <div
      id="carouselExampleControls"
      class="carousel slide"
      data-ride="carousel"
    >
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="${contextPath}/resources/images/dodo5.jpg" class="d-block w-100" alt="..." />
        </div>
        <div class="carousel-item">
          <img src="${contextPath}/resources/images/dodo5.jpg" class="d-block w-100" alt="..." />
        </div>
        <div class="carousel-item">
          <img src="${contextPath}/resources/images/dodo5.jpg" class="d-block w-100" alt="..." />
        </div>
      </div>
      <a
        class="carousel-control-prev"
        href="#carouselExampleControls"
        role="button"
        data-slide="prev"
      >
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a
        class="carousel-control-next"
        href="#carouselExampleControls"
        role="button"
        data-slide="next"
      >
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>

    <div class="img-container container category-wrap">
      <div class="row">
        <div class="col-lg-2 col-sm-2 col-md-2">
          <img src="${contextPath}/resources/images/dodo5.jpg" class="circleImg" />
          <div class="category-context">전체보기</div>
        </div>
        <div class="col-lg-2 col-sm-2 col-md-2 ">
          <img src="${contextPath}/resources/images/dodo5.jpg" class="circleImg" />
          <div class="category-context">전체보기</div>
        </div>
        <div class="col-lg-2 col-sm-2 col-md-2">
          <img src="${contextPath}/resources/images/dodo5.jpg" class="circleImg" />
          <div class="category-context">전체보기</div>
        </div>
        <div class="col-lg-2 col-sm-2 col-md-2">
          <img src="${contextPath}/resources/images/dodo5.jpg" class="circleImg" />
          <div class="category-context">전체보기</div>
        </div>
        <div class="col-lg-2 col-sm-2 col-md-2">
          <img src="${contextPath}/resources/images/dodo5.jpg" class="circleImg" />
          <div class="category-context">전체보기</div>
        </div>
        <div class="col-lg-2 col-sm-2 col-md-2">
          <img src="${contextPath}/resources/images/dodo5.jpg" class="circleImg" />
          <div class="category-context">전체보기</div>
        </div>
      </div>
    </div>

    <br />
    <br />





<script>







</script>





    <div class="container">
      <div class="sight_all">
        <span class="select_all">
        전체 보기
      </span>
        <div class="float-right"> 

          <i class="fas fa-search search_all"></i>
          &nbsp; &nbsp; &nbsp; 
          전체 
          &nbsp;
          <i class="fas fa-caret-down">
            &nbsp;&nbsp;

          </i> 추천순&nbsp;
          <i class="fas fa-caret-down"></i
          >
        </span>
      </div>
      <br />

      <hr />
    </div>
    
  	<div class='container justify-content-center' id='loadingDiv'>
  	
<div class="loadingio-spinner-magnify-6i1erl5311d"><div class="ldio-fh2riys9cfu">
<div><div><div></div><div></div></div></div>
</div></div>

</div>
    
    <div id="cocoacard">
    
    </div>
    


  
    



































    
	
	<script>




















    
	var z = new Array();

	var y = 0;
	
	
	
	var $loading = $('#loadingDiv').hide();
	
	$('#loadingDiv').fadeOut('fast')	
	
	
	
	
	$(document)
	  .ajaxStart(function () {
	  
		 
		  $loading.show();
	 
	  
	  })
	  .ajaxStop(function () {
	    $loading.hide();
	    
	    
	    $(".card").click(function(){

	        var a =  $(this).children().first().val();
	        
	       
	        
	        var url = "${contextPath}/funding/fundingView/"+a;
	        
	        
	        location.href = url;
	        
	        
	        
	        

	     })
	    
	    
	  });
	
	
	
		$(document).ready(function() {
		
	
		
		
		
	});

		window.onload = function() {

	
		$(".card").click(function(){

       var a =  $(this).children().first().val;
       
       console.log(a);

    })
	
	}














  
	
	</script>
  
  
  <script>

$(document).ready(function(){
    start.init();
});
var start = {
        param : {
            curPage : 1,
            pageListSize : 8,
        },
        
        init : function() {
          start.testAjax();
           this.testEvent();
        },
       testData : function() {
            this.setListItems("${firstData}"); // 첫 진입시 데이터 셋팅
        },
       testEvent : function() {
            // 무한 스크롤
            $(window).scroll(function() {
                // 맨 밑으로 스크롤이 갔을경우 if문을 탑니다.
                if($(window).scrollTop() == $(document).height() - $(window).height()) { 
                    start.param.curPage++; // 현재 페이지에서 +1 처리.
                    
                    start.testAjax(); //ajax 호출
                } 
            }); 
        },
        // 무한 스크롤 ajax 요청
        testAjax : function() {
            


              $.ajax({
			url:"${contextPath}/fundingApi/selectList",
			dataType : "json",
			  data     :  {curPage : start.param.curPage,
				  		   pageListSize : start.param.pageListSize	}, // 다음 페이지 번호와 페이지 사이즈를 가지고 갑니다..
      success : successCallback,
      error : errorCallback
              });






            // 성공
            function successCallback(item) {
              console.log(item);
			
			$.each(item,function(index,item){
				
				
				
				
				
				
				
				var value = $("<input type='hidden' value= "+item.fundingNo+">")
				
				var imgText = "";
				
				if(item.fileChangeName == undefined){
					
			    imgText += "'${contextPath}/resources/images/dodo5.jpg'";
			
				}else{
					
				imgText += 	"'${contextPath}/resources/uploadImages/" + item.fileChangeName+ "' ";
				
				}
				console.log(imgText);
				
				
				
				var $tempImg = $("<img src=" +imgText + "class='card-img-top' alt='...'>")
				
				
				
				
				var $card = $("<div class='card' >");
				var $boardValue = value;
				var $cardBody = $("<div class='card-body'>")
				var $cardTitle = $("<h5 class='card-title'>").text(item.fundingTitle);
				var $cardStory = $("<p class='card-text'>").text(item.fundingSummary);
				var $cardSmallForm = $("<p class='card-text'>")
				var $cardSmallCategory = $("<small class='text-muted'>").text(item.category)
				var $cardSmallAchievement = $("<small class='text-muted'>").text("달성률 : " + item.achievementRate + "%")
				var $cardSmallOrderAmount = $("<small class='text-muted'>").text("총 참여금액 :  " + item.totalOrderAmount)
				
				
				
				
				$cardSmallForm.append($cardSmallCategory,$cardSmallAchievement,$cardSmallOrderAmount)
				
				$cardBody.append($cardTitle,$cardStory,$cardSmallForm)
				
				$card.append($boardValue,$tempImg,$cardBody);
			
				z[y++] = $card;
					
			
					
				
			});

				 // 행
			
			      var kk = 0;
			      var xx = new Array();

				for(var i = 0; i<z.length-2; i++){
					
					var $cardDeck = $("<div class='card-deck'>");
					
					if(i%3 == 0){
          
						$cardDeck.append(z[(i)],z[(i+1)],z[(i+2)]);
            			
						
						
			          	xx[kk++] = $cardDeck;
			          	
			          	
					}
					console.log(xx[kk]);
					
				}

        for(var i = 0; i<xx.length; i++ ){

          $("#cocoacard").append(xx[i]);

        }
        
        if(xx.length == 0){
        	
        	$("#cocoacard").after("<h1>헉..프로젝트가 등록되어 있지 않습니다!</h1>")
        	
        	
        }
        

			
            }
            
            
            
            
            
            // 실패
            function errorCallback() {
                alert("실패");
            }
        },
        
        // 테스트 데이터 setting
        setListItems : function (list) {
            $.each(list, function(i, testData) {
            	
            	
                
               
            	
            	
            })
        }
}
 




		
				



 </script>


   
   
   <ul id="list-guestbook">
    </ul>
   
   
<script type="text/javascript">
</script>
	
	
	
	
	
	
																									
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
<jsp:include page="/WEB-INF/views/common/footer.jsp"/>

  </body>
</html>