<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <title>DowaZoo</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
      crossorigin="anonymous"
    />
    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
      integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
      integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
      crossorigin="anonymous"
    ></script>

    <link
    rel="stylesheet"
    href="https://use.fontawesome.com/releases/v5.14.0/css/all.css"
    integrity="sha384-HzLeBuhoNPvSl5KYnjx0BT+WB0QEEqLprO+NBkkk5gbc67FTaL7XIGa2w1L0Xbgc"
    crossorigin="anonymous"
  />
  
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
    <script src="https://raw.githubusercontent.com/anseki/eager-image-loader/master/eager-image-loader.min.js"></script> 
  

    <style>
      body {
        font-family: "IBMPlexSansKR-Text";
      }

      .funding-pageSelector {
        font-weight: bold;

        color: #666;
        font-size: 1.1rem;
      }

      @font-face {
        font-family: "IBMPlexSansKR-Text";
        src: url("https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_20-07@1.0/IBMPlexSansKR-Text.woff")
          format("woff");
        font-weight: normal;
        font-style: normal;
      }

      .carousel-item {
        height: 20rem;
        width: 100%;
      }

      .container {
      }
      .circleImg {
        border-radius: 50%;
      }
      .img-container {
        margin-top: 1.5%;
      }

      .category-wrap{
        text-align: center;
      }

      .category-context{
        margin-top: 6%;
        margin-left: 7%;
      }

      .search_all {
      }

      .select_all {
        
        font-size: 1.4rem;
        font-weight: bold;
      }

      .funding_menu{
        margin-top: 2%;
        margin-bottom: 2%;
      }

      .now{
        color: black;
      }
	
	
	
@keyframes ldio-fh2riys9cfu {
    0%    { transform: translate(2px,2px) }
   33.33% { transform: translate(102px,2px) }
   66.66% { transform: translate(42px,102px) }
  100%    { transform: translate(2px,2px) }
}


.ldio-fh2riys9cfu > div {
  transform: scale(0.8);
  transform-origin: 100px 100px;
}

.ldio-fh2riys9cfu > div > div {
  animation: ldio-fh2riys9cfu 1s linear infinite;
  position: absolute
}

.ldio-fh2riys9cfu > div > div div:nth-child(1) {
  width: 72px;
  height: 72px;
  border-radius: 50%;
  border: 12px solid #e90c59;
  background: #46dff0
}

.ldio-fh2riys9cfu > div > div div:nth-child(2) {
  width: 17px;
  height:  51px;
  transform: rotate(-45deg);
  background: #e90c59;
  border-radius: 0 0 8px 8px;
  position: absolute;
  top: 68px;
  left: 85px
}
.loadingio-spinner-magnify-6i1erl5311d {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: #ffffff;
}
.ldio-fh2riys9cfu {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-fh2riys9cfu div { box-sizing: content-box; }
/* generated by https://loading.io/ */


    </style>

  
  </head>
  <body>
  
	<jsp:include page="/WEB-INF/views/common/header.jsp"/>
  
    <div class="container">
      <div class="row funding-pageSelector">
        <div class="col-lg-2 col-sm-2 col-md-2 funding_menu"></div>

        <div class="col-lg-2 col-sm2 col-md-2 funding_menu"> <span class="now">펀딩 홈</span></div>
        <div class="col-lg-2 col-sm-2 col-md-2 funding_menu">카테고리</div>
        <div class="col-lg-2 col-sm-2 col-md-2 funding_menu">오픈예정</div>
        <div class="col-lg-2 col-sm-2 col-md-2 funding_menu">글로벌</div>

        <div class="col-lg-2 col-sm-2 col-md-2 funding_menu"></div>
      </div>
    </div>

    <div
      id="carouselExampleControls"
      class="carousel slide"
      data-ride="carousel"
    >
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="${contextPath}/resources/images/dodo5.jpg" class="d-block w-100" alt="..." />
        </div>
        <div class="carousel-item">
          <img src="${contextPath}/resources/images/dodo5.jpg" class="d-block w-100" alt="..." />
        </div>
        <div class="carousel-item">
          <img src="${contextPath}/resources/images/dodo5.jpg" class="d-block w-100" alt="..." />
        </div>
      </div>
      <a
        class="carousel-control-prev"
        href="#carouselExampleControls"
        role="button"
        data-slide="prev"
      >
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a
        class="carousel-control-next"
        href="#carouselExampleControls"
        role="button"
        data-slide="next"
      >
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>

    <div class="img-container container category-wrap">
      <div class="row">
        <div class="col-lg-2 col-sm-2 col-md-2">
          <img src="${contextPath}/resources/images/dodo5.jpg" class="circleImg" />
          <div class="category-context">전체보기</div>
        </div>
        <div class="col-lg-2 col-sm-2 col-md-2 ">
          <img src="${contextPath}/resources/images/dodo5.jpg" class="circleImg" />
          <div class="category-context">전체보기</div>
        </div>
        <div class="col-lg-2 col-sm-2 col-md-2">
          <img src="${contextPath}/resources/images/dodo5.jpg" class="circleImg" />
          <div class="category-context">전체보기</div>
        </div>
        <div class="col-lg-2 col-sm-2 col-md-2">
          <img src="${contextPath}/resources/images/dodo5.jpg" class="circleImg" />
          <div class="category-context">전체보기</div>
        </div>
        <div class="col-lg-2 col-sm-2 col-md-2">
          <img src="${contextPath}/resources/images/dodo5.jpg" class="circleImg" />
          <div class="category-context">전체보기</div>
        </div>
        <div class="col-lg-2 col-sm-2 col-md-2">
          <img src="${contextPath}/resources/images/dodo5.jpg" class="circleImg" />
          <div class="category-context">전체보기</div>
        </div>
      </div>
    </div>

    <br />
    <br />





<script>







</script>





    <div class="container">
      <div class="sight_all">
        <span class="select_all">
        전체 보기
      </span>
        <div class="float-right"> 

          <i class="fas fa-search search_all"></i>
          &nbsp; &nbsp; &nbsp; 
          전체 
          &nbsp;
          <i class="fas fa-caret-down">
            &nbsp;&nbsp;

          </i> 추천순&nbsp;
          <i class="fas fa-caret-down"></i
          >
        </span>
      </div>
      <br />

      <hr />
    </div>
    

   
  



                  
                  
                  <c:forEach var="funding"  varStatus="status" items="${fundingList}">
                    
                    <c:if test="${status.index %3 eq 0}">
                      <div class='card-deck'>
                      </c:if>

      <div class='card' >
		
		<input type="hidden" value="${funding.fundingNo}">
	
        <c:set var="src" value="${contextPath}/resources/uploadImages/${funding.fileChangeName}"/>
        <img src="${src}" class='card-img-top' alt='...'>

      <div class='card-body'>

        <h5 class='card-title'>
        ${funding.fundingTitle}
          </h5>

          <p class='card-text'>

            ${funding.fundingSummary}
          </p>
          <small class='text-muted'>
          
            ${funding.category}

          </small>
          <small class='text-muted'>
            ${funding.achievementRate}
          </small>

          <small class='text-muted'>

              ${funding.totalOrderAmount}

          </small>


        </div>
      </div>

      <c:if test="${status.index %3 eq 2}">
    </div>
        </c:if>




    </c:forEach>








	  <%-- 검색 파라미터가 포함된 url 생성작업 --%> 
	      <c:url var="searchParameter" value="${pInfo.boardType}">
	      	<c:if test="${!empty paramValues.ct }">
	      		<c:forEach var="ctName" items="${paramValues.ct}">
	      			<c:param name="ct" value="${ctName}"/>
	      		</c:forEach>
	      	</c:if>
	      	
	      	<c:if test="${!empty param.sVal }">
	      		<c:param name="sKey" value="${param.sKey}"/>
	      		<c:param name="sVal" value="${param.sVal}"/>
	      	</c:if>
	      	
	      
	      </c:url>
	      
	     <%--------- 검색 파라미터가 있을 경우 / 없을 경우 url 가공  -----------%>
	    <!--  검색 파라미터가 있을 경우 : search/1?ct=운동&ct=영화&sKey=tit&sVal=test&cp=2
	     검색 파라미터가 없는 경우 : list/1?cp=2
	   -->   
	    <c:choose>
	    	<%-- 검색 조건이 존재하는 경우(파라미터 cp가 쿼리스트링 제일 마지막에 추가될 수 있도록 '&' 기호 추가.) --%>
	    	<c:when test="${!empty paramValues.ct || !empty param.sVal}">
	    		<c:set var="url" value="&cp="/>
	    		<c:set var="listUrl" value="../search/${url}${pInfo.currentPage}" scope="session"/>

	    	</c:when>
	   
	   		<%-- 검색 조건이 존재하지 않는 경우 (파라미터 cp가 쿼리스트링 제일 앞에 추가될 수 있도록 '?' 기호 추가 --%>
	   		<c:otherwise>
	   			<c:set var="url" value="?cp="/>	
				<c:set var="listUrl" value="../selectList/${url}${pInfo.currentPage}" scope="session"/>
					   		
	   		</c:otherwise>
	   
	    
	    </c:choose>
	    
	    
	     
	     
	     
	     
	     
	     
		<div class="my-4">
            <ul class="pagination">
            	<c:if test="${pInfo.currentPage > pInfo.pagingBarSize}">	
            		
            		
	                <li>
	                	<!-- 맨 처음으로(<<) -->
	                    <a class="page-link text-primary" href="${url}1">&lt;&lt;</a>
	                </li>
	                
	                <li>	
	                	<!-- 이전으로(<) -->
	                	<!--  prev 생성 식 : 현제페이지 -1 / 페이징바 사이즈(10) * 10 -->
	                	<!--  fmt 태그를 이용한 소수점 제거 -->
	                	<fmt:parseNumber var="operand1" value="${(pInfo.currentPage-1)/pInfo.pagingBarSize}" integerOnly="true"/>
	               		
	               		<c:set var ="prev" value="${operand1 * 10 }"/>
	               	
	              
                   		<a class="page-link text-primary" href="${url}${prev}">&lt;</a>
	                </li>
                </c:if>
                
                <c:forEach var="p" begin="${pInfo.startPage}" end="${pInfo.endPage}">
                
                	<c:choose>
                		<c:when test="${p==pInfo.currentPage}">
                			<li><a class="page-link">${p}</a></li>
                			</c:when>
                			
                			<c:otherwise>
	                		<li>
	                			<a class="page-link text-primary" href="?cp=${p}">${p}</a>
		                	</li>
		                	</c:otherwise>
		            </c:choose>	
                </c:forEach>
                
                
                <!-- 다음 페이지로(>) -->
                <!--  next 생성 식 : (현재 페이지 + (pInfo.pagingBarSize-1) ) /10 * 10 + 1  -->
                <c:if test="${pInfo.maxPage > pInfo.endPage}">
                
               
	                <li>
	                <fmt:parseNumber var="operand2" value="${(pInfo.currentPage +(pInfo.pagingBarSize-1))/10 }" integerOnly="true"/>
                	<c:set var="next" value="${operand2 * 10 + 1}"/>
            
						<a class="page-link text-primary" href="${url}${next}">&gt;</a>
	                </li>
	                
	                <!-- 맨 끝으로(>>) -->
	                <li>
	                    <a class="page-link text-primary" href="${url}${pInfo.maxPage}">&gt;&gt;</a>
	                </li>
	            </c:if>
	                
	                
                
            </ul>
        </div>	








    </div>


	
	
	<script>
	
	
	
	
	 $(".card").click(function(){

	        var a =  $(this).children().first().val();
	        
	       
	        
	        var url = "${contextPath}/funding/fundingView/"+a;
	        
	        
	        location.href = url;
	        
	        
	        
	        

	     });
	
	
	</script>
											
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
<jsp:include page="/WEB-INF/views/common/footer.jsp"/>

  </body>
</html>